### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="e6c6f-101">练习-连接 Azure 存储配置</span><span class="sxs-lookup"><span data-stu-id="e6c6f-101">Exercise - Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="e6c6f-102">使用 Azure 存储配置进行连接</span><span class="sxs-lookup"><span data-stu-id="e6c6f-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="e6c6f-103">使用 Azure 存储配置进行连接</span><span class="sxs-lookup"><span data-stu-id="e6c6f-103">Connect with your Azure Storage configuration</span></span>
  ms.date: 01/15/2019
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 98744a5d48b1a2a8301d9f169dc82ced600f6f9a
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2138206"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
