### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="8c404-101">练习-将 Azure 存储配置添加到应用</span><span class="sxs-lookup"><span data-stu-id="8c404-101">Exercise - Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="8c404-102">向您的应用程序添加 Azure 存储配置</span><span class="sxs-lookup"><span data-stu-id="8c404-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="8c404-103">向您的应用程序添加 Azure 存储配置</span><span class="sxs-lookup"><span data-stu-id="8c404-103">Add Azure Storage configuration to your app</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 584899221bf19fe039cac692b05e426f411c3866
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136623"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]'
