### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: 为 Redis 配置 Azure 缓存
metadata:
  title: 为 Redis 配置 Azure 缓存
  description: 为 Redis 配置 Azure 缓存
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: a18fe517364a93549086fe2eb7840db6b979981f
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136843"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
