### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: 确定应用程序中的性能瓶颈
metadata:
  title: 确定应用程序中的性能瓶颈
  description: 在此单元中, 我们将讨论如何识别应用程序中的性能瓶颈
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: f301ea82e48b457408ddfe5f168239b2840fe86a
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2138070"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 查看你的知识
  questions:
  - content: 以下哪一项最恰当地介绍了 Application Insights？
    choices:
    - content: 在 Azure 中实现所有监控需求的单一视图
      isCorrect: false
      explanation: 虽然 application Insights 可以提供大量的应用程序性能数据, 但它并不是一个全面的 Azure 监视解决方案。
    - content: 运行状况终结点监视模式的实现
      isCorrect: false
      explanation: 运行状况终结点监视模式侧重于监视由应用程序公开的用于整体运行状况的终结点。
    - content: 启用跨基础结构和应用程序收集日志的工作区
      isCorrect: false
      explanation: 日志分析是一个可跨基础结构和应用程序收集日志的工作区。
    - content: 用于监视 web 应用程序的可用性、性能和使用情况的服务
      isCorrect: true
      explanation: Application Insights 是一种用于监视 web 应用程序的可用性、性能和使用情况的服务。
  - content: 'True 或 false: Log Analytics 跟踪自定义日志和指标。'
    choices:
    - content: "True"
      isCorrect: true
      explanation: 对于自定义日志和指标, 可以使用 HTTP 数据收集器 API 将数据写入来自任何 REST API 客户端或 Azure 逻辑应用程序的 Log Analytics, 以从自定义工作流中写入数据。
    - content: "False"
      isCorrect: false
      explanation: 对于自定义日志和指标, 可以使用 HTTP 数据收集器 API 将数据写入来自任何 REST API 客户端或 Azure 逻辑应用程序的 Log Analytics, 以从自定义工作流中写入数据。
