### YamlMime:ModuleUnit
uid: learn.secure-your-azure-sql-database.4-data-security
metadata:
  title: 在传输、静止和显示时保护数据
  description: 数据安全性
  ms.date: 11/09/2018
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 99f7a43cd60e9ddab1e1e5e7c9fddc62717bfb5d
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137127"
interactive: bash
azureSandbox: true
title: 在传输、静止和显示时保护数据
durationInMinutes: 8
content: '[!include[](includes/4-data-security.md)]'
