### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="78b1f-101">安全设计</span><span class="sxs-lookup"><span data-stu-id="78b1f-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="78b1f-102">安全设计</span><span class="sxs-lookup"><span data-stu-id="78b1f-102">Design for security</span></span>
  description: <span data-ttu-id="78b1f-103">安全设计</span><span class="sxs-lookup"><span data-stu-id="78b1f-103">Design for security</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: d874cbac910948c6e67cc29063eba760ff30d482
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136385"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="78b1f-104">查看你的知识</span><span class="sxs-lookup"><span data-stu-id="78b1f-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="78b1f-105">以下哪种类型的数据可能需要安全保护？</span><span class="sxs-lookup"><span data-stu-id="78b1f-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="78b1f-106">包含个人信息的客户数据</span><span class="sxs-lookup"><span data-stu-id="78b1f-106">Customer data that contains personal information</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-107">为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。</span><span class="sxs-lookup"><span data-stu-id="78b1f-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="78b1f-108">财务数据支持业务运营</span><span class="sxs-lookup"><span data-stu-id="78b1f-108">Financial data supporting business operations</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-109">为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。</span><span class="sxs-lookup"><span data-stu-id="78b1f-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="78b1f-110">知识产权</span><span class="sxs-lookup"><span data-stu-id="78b1f-110">Intellectual property</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-111">为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。</span><span class="sxs-lookup"><span data-stu-id="78b1f-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="78b1f-112">上述所有可能都需要安全保护</span><span class="sxs-lookup"><span data-stu-id="78b1f-112">All of the above may need security protections</span></span>
      isCorrect: true
      explanation: <span data-ttu-id="78b1f-113">以上所有情况都可能会给出额外的安全保护。</span><span class="sxs-lookup"><span data-stu-id="78b1f-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="78b1f-114">以下哪一项是您可能会在策略 & 访问层中看到的攻击示例？</span><span class="sxs-lookup"><span data-stu-id="78b1f-114">Which of the following is an example of an attack you might see at the policies & access layer?</span></span>
    choices:
    - content: <span data-ttu-id="78b1f-115">在线发布的公开凭据</span><span class="sxs-lookup"><span data-stu-id="78b1f-115">Exposed credentials posted online</span></span>
      isCorrect: true
      explanation: <span data-ttu-id="78b1f-116">公开的凭据是组织的巨大风险, 在策略 & 访问层中应用。</span><span class="sxs-lookup"><span data-stu-id="78b1f-116">Exposed credentials are a huge risk to an organization and apply at the policies & access layer.</span></span>
    - content: <span data-ttu-id="78b1f-117">SYN 泛滥攻击</span><span class="sxs-lookup"><span data-stu-id="78b1f-117">A SYN flood attack</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-118">SYN 洪水攻击是一种在网络外围通常会看到的拒绝服务攻击类型。</span><span class="sxs-lookup"><span data-stu-id="78b1f-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="78b1f-119">在不提供凭据的情况下将员工加入数据中心</span><span class="sxs-lookup"><span data-stu-id="78b1f-119">Following an employee into a datacenter without presenting credentials</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-120">将员工关注数据中心是物理层攻击。</span><span class="sxs-lookup"><span data-stu-id="78b1f-120">Following an employee into a datacenter is a physical layer attack.</span></span>
    - content: <span data-ttu-id="78b1f-121">加密虚拟机的磁盘的勒索软件</span><span class="sxs-lookup"><span data-stu-id="78b1f-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      explanation: <span data-ttu-id="78b1f-122">勒索软件攻击是虚拟机/计算层攻击。</span><span class="sxs-lookup"><span data-stu-id="78b1f-122">Ransomware attacks are a VM/compute layer attack.</span></span>
