### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: 安全设计
metadata:
  title: 安全设计
  description: 安全设计
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: d874cbac910948c6e67cc29063eba760ff30d482
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136385"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 查看你的知识
  questions:
  - content: 以下哪种类型的数据可能需要安全保护？
    choices:
    - content: 包含个人信息的客户数据
      isCorrect: false
      explanation: 为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。
    - content: 财务数据支持业务运营
      isCorrect: false
      explanation: 为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。
    - content: 知识产权
      isCorrect: false
      explanation: 为此数据提供正确的安全保护非常重要, 但这并不是唯一的正确选择。
    - content: 上述所有可能都需要安全保护
      isCorrect: true
      explanation: 以上所有情况都可能会给出额外的安全保护。
  - content: 以下哪一项是您可能会在策略 & 访问层中看到的攻击示例？
    choices:
    - content: 在线发布的公开凭据
      isCorrect: true
      explanation: 公开的凭据是组织的巨大风险, 在策略 & 访问层中应用。
    - content: SYN 泛滥攻击
      isCorrect: false
      explanation: SYN 洪水攻击是一种在网络外围通常会看到的拒绝服务攻击类型。
    - content: 在不提供凭据的情况下将员工加入数据中心
      isCorrect: false
      explanation: 将员工关注数据中心是物理层攻击。
    - content: 加密虚拟机的磁盘的勒索软件
      isCorrect: false
      explanation: 勒索软件攻击是虚拟机/计算层攻击。
