### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: 在 Azure 中配置、部署和运行
metadata:
  title: 在 Azure 中配置、部署和运行
  description: 在 Azure 中配置、部署和运行
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: e9f999032cbf338d9b29f75929f19e59ac3d5a1a
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136169"
durationInMinutes: 12
interactive: bash
azureSandbox: true
content: >
  [!include[](includes/6-configure-deploy-run-azure.md)]
tasks:
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.Web/sites
  hint: 使用上面的说明创建 web 应用程序并部署网站。
