### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: 选择你的帐户设置
metadata:
  title: 选择你的帐户设置
  description: 选择你的帐户设置
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: aad1cf9d3b07fe699cbb827cc0a4363712786394
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137050"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
