### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="acf8a-101">创建 Azure IoT 中心应用程序</span><span class="sxs-lookup"><span data-stu-id="acf8a-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="acf8a-102">创建 Azure IoT 中心应用程序</span><span class="sxs-lookup"><span data-stu-id="acf8a-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="acf8a-103">创建 Azure IoT 中心应用程序</span><span class="sxs-lookup"><span data-stu-id="acf8a-103">Create an Azure IoT Central application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 1c131e1bb1b76f0f0c6690a64c907a14180597bc
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136239"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
