### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: <span data-ttu-id="2d9a9-101">将模拟咖啡机连接到应用程序</span><span class="sxs-lookup"><span data-stu-id="2d9a9-101">Connect your simulated coffee machine to the application</span></span>
metadata:
  title: <span data-ttu-id="2d9a9-102">将模拟咖啡机连接到应用程序</span><span class="sxs-lookup"><span data-stu-id="2d9a9-102">Connect your simulated coffee machine to the application</span></span>
  description: <span data-ttu-id="2d9a9-103">将模拟咖啡机连接到应用程序</span><span class="sxs-lookup"><span data-stu-id="2d9a9-103">Connect your simulated coffee machine to the application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 3973e10aada6ead4b026e6fdfe0986d7764649ba
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136590"
interactive: bash
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
