### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: 使用 azure 门户启用和配置 azure VM 磁盘缓存
metadata:
  title: 使用 azure 门户启用和配置 azure VM 磁盘缓存
  description: 使用 azure 门户启用和配置 azure VM 磁盘缓存
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 7861f918a669dc106f128c10a68231e7da8018e6
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136560"
durationInMinutes: 5
content: '[! include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)'
