### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: <span data-ttu-id="2a492-101">使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="2a492-101">Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="2a492-102">使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="2a492-102">Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="2a492-103">使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="2a492-103">Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 057f8b5f6c2d38d73af52c33670506222d4c2b02
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136564"
durationInMinutes: 5
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
