### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: <span data-ttu-id="f039f-101">练习-使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="f039f-101">Exercise - Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="f039f-102">练习-使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="f039f-102">Exercise - Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="f039f-103">练习-使用 PowerShell 管理缓存设置</span><span class="sxs-lookup"><span data-stu-id="f039f-103">Exercise - Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: bcc461dbc74093fd6ef21384aa0715f829889fee
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136768"
interactive: powershell
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]'
