### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.4-exercise-implement-a-web-application
title: 练习-编写代码以实现 web 应用程序
metadata:
  title: 练习-编写代码以实现 web 应用程序
  description: 练习-编写代码以实现 web 应用程序
  ms.date: 12/12/2018
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-java-node
  ms.openlocfilehash: d24d420120758728f552e1d41fb39f4aabc7f472
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137322"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-implement-a-web-application.md)]'
