### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.4-exercise-implement-a-web-application
title: <span data-ttu-id="72598-101">练习-编写代码以实现 web 应用程序</span><span class="sxs-lookup"><span data-stu-id="72598-101">Exercise - Write code to implement a web application</span></span>
metadata:
  title: <span data-ttu-id="72598-102">练习-编写代码以实现 web 应用程序</span><span class="sxs-lookup"><span data-stu-id="72598-102">Exercise - Write code to implement a web application</span></span>
  description: <span data-ttu-id="72598-103">练习-编写代码以实现 web 应用程序</span><span class="sxs-lookup"><span data-stu-id="72598-103">Exercise - Write code to implement a web application</span></span>
  ms.date: 12/12/2018
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-java-node
  ms.openlocfilehash: d24d420120758728f552e1d41fb39f4aabc7f472
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137322"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-implement-a-web-application.md)]'
