### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: <span data-ttu-id="2fe20-101">设置环境变量</span><span class="sxs-lookup"><span data-stu-id="2fe20-101">Set environment variables</span></span>
  description: <span data-ttu-id="2fe20-102">在 Azure 容器实例中设置环境变量。</span><span class="sxs-lookup"><span data-stu-id="2fe20-102">Set environment variables in Azure Container Instances.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 852eaa00760e0f6933b4449f7f1378d997bb03b0
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2138216"
title: <span data-ttu-id="2fe20-103">设置环境变量</span><span class="sxs-lookup"><span data-stu-id="2fe20-103">Set environment variables</span></span>
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: >
  [!include[](includes/4-use-environment-variables.md)]
tasks:
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.ContainerInstance/containerGroups
      name: aci-demo
  hint: ''
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.ContainerInstance/containerGroups
      name: aci-demo-secure
  hint: ''
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.DocumentDB/databaseAccounts
      kind: GlobalDocumentDB
  hint: ''
