### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: 配置和初始化客户端库
metadata:
  title: 配置和初始化客户端库
  description: 配置和初始化客户端库
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: f79987228c4ee6c48218194c24d8ccf949445d9d
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137701"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
