### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="8a164-101">将应用程序配置为通过事件中心发送或接收邮件</span><span class="sxs-lookup"><span data-stu-id="8a164-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="8a164-102">将应用程序配置为通过事件中心发送或接收邮件</span><span class="sxs-lookup"><span data-stu-id="8a164-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="8a164-103">将应用程序配置为通过事件中心发送或接收邮件</span><span class="sxs-lookup"><span data-stu-id="8a164-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 9c91b483b7519c3526ed80f597a046b460b6347b
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2137411"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
